language: node_js
node_js:
  - 14

jobs:
  include:
    - stage: "test"
      before_script: npm run lint
      script: npm test
    - stage: "deploy"
      script: npm run build
      deploy:
        provider: s3
        bucket: www.coommuter.com
        region: eu-north-1
        local_dir: ./dist
        verbose: true
        edge: true # opt in to dpl v2
        on:
          branch: ["master"]